// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/2/2026, 3:41:05 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/kkaranja/kevin/payroll-landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kkaranja/kevin/payroll-landing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kkaranja/kevin/payroll-landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kkaranja/kevin/payroll-landing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kkaranja/kevin/payroll-landing/plugins/**/*.{js,ts,mjs}","/home/kkaranja/kevin/payroll-landing/composables/**/*.{js,ts,mjs}","/home/kkaranja/kevin/payroll-landing/utils/**/*.{js,ts,mjs}","/home/kkaranja/kevin/payroll-landing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kkaranja/kevin/payroll-landing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/kkaranja/kevin/payroll-landing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/kkaranja/kevin/payroll-landing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;